# action.yml
name: 'Bump-N-Tag Version'
description: 'Increment version and tag them'
author: 'Vinodh Raj'
branding:
  icon: 'git-commit'
  color: 'red'
inputs:
  file_name:  # id of input
    description: 'Name of the version file'
    required: true
    default: 'version'
  tag_version: # id
    description: 'States whether to create tag for this version or not'
    required: false
    default: 'false'
  do_file_bump: # id
    description: 'Whether to auto-bump the version file, or just use the version from it'
    required: false
    default: 'true'
outputs:
  app_version: # id of output
    description: 'Version from given file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file_name }} 
    - ${{ inputs.tag_version }}
    - ${{ inputs.do_file_bump }}
